### ISSUE TITLE
How to set context-variables?

### ISSUE THREAD

**Issue by nuil** [app-insights-php/app-insights-php-bundle#23]
Hi,

I would like to use some custom context-variables like the ApplicationContext or the UserContext for the automatically generated events. 

How can I do it?

**Comment by norzechowicz** [comment]
Hey @nuil, first of all I'm happy that you are thinking about using this bundle! It was created for project I'm currently working on and we didn't had to set those things so far, that's feature you are asking about it's not available yet out of the box. 
I'm not sure if that makes sense for you but you might want to register additional HttpRequestListener, similar to the [original one](https://github.com/app-insights-php/app-insights-php-bundle/blob/master/Listener/HttpRequestListener.php#L23) or maybe KernelTerminateListener, like [this one](https://github.com/app-insights-php/app-insights-php-bundle/blob/master/Listener/KernelTerminateListener.php#L21) and simply access Application/User context using one of below methods: 

![image](https://user-images.githubusercontent.com/1921950/66353098-8987f900-e961-11e9-88bb-7980bd2d93d9.png)

This is also really nice use case so we might want to think about some build in extension point that would let you access those contexts in specific, defined by bundle extension points. 

If you would let me know what exactly you want to set on the contexts I might be able to a better solution for you. 

Please let me know what you think!

**Comment by nuil** [comment]
Hi @norzechowicz, thanks for your reply.
I want to send the application-version to Insights. During our build-process the Version will be stored in an env variable so I can access the value during runtime.

I created a onTerminate subscriber like you suggested. But unfortunatly I do not see the version in Insights.  
![Bildschirmfoto 2019-10-08 um 08 32 44](https://user-images.githubusercontent.com/2334194/66372444-4c922580-e9a6-11e9-9f8c-bdb5317b6e59.png)

The logs are showing that my subscriber is called before yours, so maybe I'm just looking at the wrong places in Insights.

I will try to create a pullrequest later, so you can enrich the context via the configuration, so something like this will be possible
![image](https://user-images.githubusercontent.com/2334194/66372684-e659d280-e9a6-11e9-9f22-8dc65bf1685e.png)

**Comment by norzechowicz** [comment]
Application version is something we might want to add directly into the [ClientFactory](https://github.com/app-insights-php/client/blob/master/src/AppInsightsPHP/Client/ClientFactory.php) and then allow to set it up through the bundle [Configuration](https://github.com/app-insights-php/app-insights-php-bundle/blob/master/DependencyInjection/Configuration.php)
