### ISSUE TITLE
Upgrade to Symfony 5

### ISSUE THREAD

**Issue by smindel** [app-insights-php/app-insights-php-bundle#25]
Your bundle is exactly what we need. Unfortunately we are using Symfony 5.0. Do you have any plans to upgrade?

**Comment by norberttech** [comment]
Hey @smindel I'm happy to hear that, I think that the update should be pretty straight forward, will see what I can do

**Comment by norberttech** [comment]
https://github.com/app-insights-php/app-insights-php-bundle/releases/tag/0.2.3 here you go, please let me know if that works for you, I don't have any symfony 5 based project to test it
