### ISSUE TITLE
AppInsightsPHP/Client/Client::endRequest fails if module is disabled

### ISSUE THREAD

**Issue by smindel** [app-insights-php/app-insights-php-bundle#31]
If the module is disabled, HttpRequestListener->request will not be set in HttpRequestListener::onKernelRequest(), so that when it is passed to AppInsightsPHP\Client\Client::endRequest() in HttpRequestListener::onKernelResponse() an invalid argument error is triggered.

**Comment by norberttech** [comment]
Good catch, any chance you could provide a fix for HttpRequestListener that would not go further is client is disabled?

**Comment by tomaszhanc** [comment]
I think it's fixed now thanks to https://github.com/app-insights-php/app-insights-php-bundle/pull/35
