### ISSUE TITLE
PHP SDK | Does it capture method names as part of telemetry?

### ISSUE THREAD

**Issue by vikram404** [app-insights-php/app-insights-php-bundle#41]
We have added the App Insights PHP SDK to a PHP web App running on Azure App Service and this communicates with a Azure Database for mySQL. Had the following questions:
1. In the end to end transaction details blade of App Insights - we are observing only the GET and POST requests. Is the information capture at this level only or is there a way to turn on capture of PHP methods so we can measure performance?
 ![Im01](https://user-images.githubusercontent.com/10514410/107637012-827aa480-6c93-11eb-8a31-16ecd9843670.png)

2. The Application Map is not showing the connection from the App to the DB. Is this not enabled for PHP?

3. The Live Metrics View does not show any Sample Telemetry - is there a way to enable that? 
![Im02](https://user-images.githubusercontent.com/10514410/107637015-83abd180-6c93-11eb-928a-ab0d158230e9.png)

**Comment by norberttech** [comment]
> In the end to end transaction details blade of App Insights - we are observing only the GET and POST requests. Is the information capture at this level only or is there a way to turn on capture of PHP methods so we can measure performance?

No, PHP App Insigts does not track PHP method execution, that would be highly inefficient. If you want to profile your production PHP code, please look into https://www.blackfire.io/ or simila profiler.

> The Application Map is not showing the connection from the App to the DB. Is this not enabled for PHP?

You can use this https://github.com/app-insights-php/doctrine-dependency-logger to track dp dependency but expect performance degradation. 

> The Live Metrics View does not show any Sample Telemetry - is there a way to enable that?

This library does not collect telemetry from the system/server.
